// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type ChatAnswer struct {
	Question    string      `json:"question"`
	SQL         string      `json:"sql"`
	Blocked     bool        `json:"blocked"`
	BlockReason *string     `json:"blockReason,omitempty"`
	Columns     []string    `json:"columns"`
	Rows        [][]*string `json:"rows"`
	Explanation string      `json:"explanation"`
}

type CohortRow struct {
	CohortMonth   string  `json:"cohortMonth"`
	ActivityMonth string  `json:"activityMonth"`
	Customers     int     `json:"customers"`
	RetentionPct  float64 `json:"retentionPct"`
}

type GeneratedContent struct {
	ProductID string      `json:"productId"`
	Kind      ContentKind `json:"kind"`
	Content   string      `json:"content"`
}

type ImportJob struct {
	ID          string     `json:"id"`
	StoreID     *string    `json:"storeId,omitempty"`
	Filename    string     `json:"filename"`
	Platform    Platform   `json:"platform"`
	State       JobState   `json:"state"`
	RowsParsed  int        `json:"rowsParsed"`
	RowsSkipped int        `json:"rowsSkipped"`
	Warnings    []string   `json:"warnings,omitempty"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
	FinishedAt  *time.Time `json:"finishedAt,omitempty"`
	Error       *string    `json:"error,omitempty"`
}

type Insight struct {
	Summary    string   `json:"summary"`
	Highlights []string `json:"highlights"`
	Actions    []string `json:"actions"`
}

type Metrics struct {
	RevenueCents       int             `json:"revenueCents"`
	Orders             int             `json:"orders"`
	AovCents           int             `json:"aovCents"`
	UnitsSold          int             `json:"unitsSold"`
	NewCustomers       int             `json:"newCustomers"`
	ReturningCustomers int             `json:"returningCustomers"`
	ReturningRate      float64         `json:"returningRate"`
	TopProducts        []*ProductStat  `json:"topProducts"`
	BottomProducts     []*ProductStat  `json:"bottomProducts"`
	DeadStock          []*VariantStat  `json:"deadStock"`
	Trend              []*TimePoint    `json:"trend"`
	CohortRetention    []*CohortRow    `json:"cohortRetention"`
	InventoryVelocity  []*VelocityStat `json:"inventoryVelocity"`
}

type Mutation struct {
}

type Product struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	ProductType *string  `json:"productType,omitempty"`
	Vendor      *string  `json:"vendor,omitempty"`
	Tags        []string `json:"tags"`
}

type ProductStat struct {
	ProductID    string `json:"productId"`
	Title        string `json:"title"`
	RevenueCents int    `json:"revenueCents"`
	UnitsSold    int    `json:"unitsSold"`
}

type Query struct {
}

type Store struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Platform   Platform  `json:"platform"`
	ImportedAt time.Time `json:"importedAt"`
}

type Subscription struct {
}

type TimePoint struct {
	Date         string `json:"date"`
	RevenueCents int    `json:"revenueCents"`
	Orders       int    `json:"orders"`
}

type VariantStat struct {
	VariantID         string  `json:"variantId"`
	Sku               *string `json:"sku,omitempty"`
	Title             string  `json:"title"`
	InventoryQty      int     `json:"inventoryQty"`
	DaysSinceLastSale int     `json:"daysSinceLastSale"`
}

type VelocityStat struct {
	VariantID      string  `json:"variantId"`
	Sku            *string `json:"sku,omitempty"`
	Title          string  `json:"title"`
	UnitsPer30Days float64 `json:"unitsPer30Days"`
	UnitsPer90Days float64 `json:"unitsPer90Days"`
	InventoryQty   int     `json:"inventoryQty"`
}

type AIProvider string

const (
	AIProviderOllama   AIProvider = "OLLAMA"
	AIProviderLmstudio AIProvider = "LMSTUDIO"
)

var AllAIProvider = []AIProvider{
	AIProviderOllama,
	AIProviderLmstudio,
}

func (e AIProvider) IsValid() bool {
	switch e {
	case AIProviderOllama, AIProviderLmstudio:
		return true
	}
	return false
}

func (e AIProvider) String() string {
	return string(e)
}

func (e *AIProvider) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AIProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AIProvider", str)
	}
	return nil
}

func (e AIProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ContentKind string

const (
	ContentKindDescription ContentKind = "DESCRIPTION"
	ContentKindSeo         ContentKind = "SEO"
	ContentKindEmail       ContentKind = "EMAIL"
)

var AllContentKind = []ContentKind{
	ContentKindDescription,
	ContentKindSeo,
	ContentKindEmail,
}

func (e ContentKind) IsValid() bool {
	switch e {
	case ContentKindDescription, ContentKindSeo, ContentKindEmail:
		return true
	}
	return false
}

func (e ContentKind) String() string {
	return string(e)
}

func (e *ContentKind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentKind", str)
	}
	return nil
}

func (e ContentKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type JobState string

const (
	JobStatePending JobState = "PENDING"
	JobStateRunning JobState = "RUNNING"
	JobStateDone    JobState = "DONE"
	JobStateFailed  JobState = "FAILED"
)

var AllJobState = []JobState{
	JobStatePending,
	JobStateRunning,
	JobStateDone,
	JobStateFailed,
}

func (e JobState) IsValid() bool {
	switch e {
	case JobStatePending, JobStateRunning, JobStateDone, JobStateFailed:
		return true
	}
	return false
}

func (e JobState) String() string {
	return string(e)
}

func (e *JobState) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobState", str)
	}
	return nil
}

func (e JobState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Platform string

const (
	PlatformShopify     Platform = "SHOPIFY"
	PlatformAmazon      Platform = "AMAZON"
	PlatformWoocommerce Platform = "WOOCOMMERCE"
)

var AllPlatform = []Platform{
	PlatformShopify,
	PlatformAmazon,
	PlatformWoocommerce,
}

func (e Platform) IsValid() bool {
	switch e {
	case PlatformShopify, PlatformAmazon, PlatformWoocommerce:
		return true
	}
	return false
}

func (e Platform) String() string {
	return string(e)
}

func (e *Platform) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Platform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Platform", str)
	}
	return nil
}

func (e Platform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
