package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"cartograph/api/graph/generated"
	"cartograph/api/graph/model"
	"cartograph/api/internal/ai"
	"cartograph/api/internal/analytics"
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ImportStore is the resolver for the importStore field.
func (r *mutationResolver) ImportStore(ctx context.Context, filename string, platform model.Platform) (*model.ImportJob, error) {
	var jobID string
	err := r.DB.QueryRow(ctx, `
		INSERT INTO import_jobs (filename, platform, state)
		VALUES ($1, $2, 'pending')
		RETURNING id::TEXT
	`, filename, string(platform)).Scan(&jobID)
	if err != nil {
		return nil, fmt.Errorf("create import job: %w", err)
	}

	// Notify worker — non-fatal if it fails (worker polls)
	_, _ = r.DB.Exec(ctx, "SELECT pg_notify('import_jobs', $1)", jobID)

	return &model.ImportJob{
		ID:       jobID,
		Filename: filename,
		Platform: platform,
		State:    model.JobStatePending,
	}, nil
}

// Ask is the resolver for the ask field.
func (r *mutationResolver) Ask(ctx context.Context, storeID string, question string) (*model.ChatAnswer, error) {
	sid, err := uuid.Parse(storeID)
	if err != nil {
		return nil, fmt.Errorf("invalid storeId: %w", err)
	}

	res := r.AIClient.Ask(ctx, sid, question)

	// Log best-effort — don't fail the request if audit log insert fails.
	_, _ = r.DB.Exec(ctx, `
		INSERT INTO chat_queries (store_id, question, generated_sql, was_blocked, rows_returned)
		VALUES ($1, $2, $3, $4, $5)
	`, sid, question, res.SQL, res.Blocked, len(res.Rows))

	ans := &model.ChatAnswer{
		Question:    question,
		SQL:         res.SQL,
		Blocked:     res.Blocked,
		Columns:     res.Columns,
		Rows:        res.Rows,
		Explanation: res.Explanation,
	}
	if res.BlockReason != "" {
		ans.BlockReason = &res.BlockReason
	}
	if ans.Columns == nil {
		ans.Columns = []string{}
	}
	if ans.Rows == nil {
		ans.Rows = [][]*string{}
	}
	return ans, nil
}

// GenerateContent is the resolver for the generateContent field.
func (r *mutationResolver) GenerateContent(ctx context.Context, productIds []string, kind model.ContentKind) ([]*model.GeneratedContent, error) {
	products, err := fetchProductsForContent(ctx, r.DB, productIds)
	if err != nil {
		return nil, err
	}

	results, err := r.AIClient.GenerateContent(ctx, products, string(kind))
	if err != nil {
		return nil, err
	}

	out := make([]*model.GeneratedContent, len(results))
	for i, res := range results {
		out[i] = &model.GeneratedContent{
			ProductID: res.ProductID,
			Kind:      kind,
			Content:   res.Content,
		}
	}
	return out, nil
}

// Stores is the resolver for the stores field.
func (r *queryResolver) Stores(ctx context.Context) ([]*model.Store, error) {
	rows, err := r.DB.Query(ctx, `
		SELECT id::TEXT, name, platform, imported_at
		FROM stores ORDER BY imported_at DESC
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var stores []*model.Store
	for rows.Next() {
		var s model.Store
		if err := rows.Scan(&s.ID, &s.Name, &s.Platform, &s.ImportedAt); err != nil {
			return nil, err
		}
		stores = append(stores, &s)
	}
	return stores, rows.Err()
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, storeID string, from *time.Time, to *time.Time, platform *model.Platform) (*model.Metrics, error) {
	sid, err := uuid.Parse(storeID)
	if err != nil {
		return nil, fmt.Errorf("invalid storeId: %w", err)
	}

	f := analytics.MetricsFilter{StoreID: sid}
	if from != nil {
		f.From = *from
	}
	if to != nil {
		f.To = *to
	}

	m, err := analytics.Compute(ctx, r.DB, f)
	if err != nil {
		return nil, err
	}
	return metricsToModel(m), nil
}

// Insight is the resolver for the insight field.
func (r *queryResolver) Insight(ctx context.Context, storeID string, from *time.Time, to *time.Time) (*model.Insight, error) {
	sid, err := uuid.Parse(storeID)
	if err != nil {
		return nil, fmt.Errorf("invalid storeId: %w", err)
	}

	f := analytics.MetricsFilter{StoreID: sid}
	if from != nil {
		f.From = *from
	}
	if to != nil {
		f.To = *to
	}

	m, err := analytics.Compute(ctx, r.DB, f)
	if err != nil {
		return nil, err
	}

	out, _ := r.AIClient.GenerateNarrative(ctx, ai.NarrativeInput{
		Metrics: m,
		From:    f.From.Format("2006-01-02"),
		To:      f.To.Format("2006-01-02"),
	})
	if out == nil {
		return &model.Insight{Summary: "AI unavailable.", Highlights: []string{}, Actions: []string{}}, nil
	}
	return &model.Insight{
		Summary:    out.Summary,
		Highlights: out.Highlights,
		Actions:    out.Actions,
	}, nil
}

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, storeID string, query string, limit *int) ([]*model.Product, error) {
	sid, err := uuid.Parse(storeID)
	if err != nil {
		return nil, fmt.Errorf("invalid storeId: %w", err)
	}

	lim := 10
	if limit != nil {
		lim = *limit
	}

	results, err := analytics.SearchProducts(ctx, r.DB, r.AIClient.OllamaURL(), sid, query, lim)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Product, len(results))
	for i, p := range results {
		prod := &model.Product{ID: p.ID, Title: p.Title, Tags: p.Tags}
		if p.Description != "" {
			prod.Description = &p.Description
		}
		if p.ProductType != "" {
			prod.ProductType = &p.ProductType
		}
		if p.Vendor != "" {
			prod.Vendor = &p.Vendor
		}
		out[i] = prod
	}
	return out, nil
}

// ImportJob is the resolver for the importJob field.
func (r *queryResolver) ImportJob(ctx context.Context, id string) (*model.ImportJob, error) {
	return queryImportJob(ctx, r.DB, id)
}

// ImportProgress is the resolver for the importProgress field.
func (r *subscriptionResolver) ImportProgress(ctx context.Context, jobID string) (<-chan *model.ImportJob, error) {
	ch := make(chan *model.ImportJob, 4)

	go func() {
		defer close(ch)

		notifCh, unsub := r.PubSub.Subscribe("import_progress")
		defer unsub()

		// Send initial state immediately
		if job, err := queryImportJob(ctx, r.DB, jobID); err == nil && job != nil {
			select {
			case ch <- job:
			case <-ctx.Done():
				return
			}
			if job.State == model.JobStateDone || job.State == model.JobStateFailed {
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-notifCh:
				if !ok {
					return
				}
				if payload != jobID {
					continue
				}
				job, err := queryImportJob(ctx, r.DB, jobID)
				if err != nil || job == nil {
					return
				}
				select {
				case ch <- job:
				case <-ctx.Done():
					return
				}
				if job.State == model.JobStateDone || job.State == model.JobStateFailed {
					return
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func queryImportJob(ctx context.Context, db *pgxpool.Pool, id string) (*model.ImportJob, error) {
	var j model.ImportJob
	var storeID *string
	var startedAt, finishedAt *time.Time
	var errMsg *string
	var warnings []string

	row := db.QueryRow(ctx, `
		SELECT id::TEXT, store_id::TEXT, filename, platform, state,
		       rows_parsed, rows_skipped,
		       COALESCE((SELECT array_agg(w) FROM jsonb_array_elements_text(COALESCE(warnings, '[]'::jsonb)) w), '{}'),
		       started_at, finished_at, error
		FROM import_jobs WHERE id = $1
	`, id)

	err := row.Scan(&j.ID, &storeID, &j.Filename, &j.Platform, &j.State,
		&j.RowsParsed, &j.RowsSkipped, &warnings, &startedAt, &finishedAt, &errMsg)
	if err != nil {
		return nil, err
	}
	j.StoreID = storeID
	j.StartedAt = startedAt
	j.FinishedAt = finishedAt
	j.Error = errMsg
	j.Warnings = warnings
	return &j, nil
}
func fetchProductsForContent(ctx context.Context, db *pgxpool.Pool, ids []string) ([]ai.ProductInput, error) {
	rows, err := db.Query(ctx, `
		SELECT id::TEXT, title, COALESCE(description,''), COALESCE(product_type,''),
		       COALESCE(vendor,''), COALESCE(tags,'{}')
		FROM products WHERE id = ANY($1::uuid[])
	`, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var products []ai.ProductInput
	for rows.Next() {
		var p ai.ProductInput
		var tags []string
		if err := rows.Scan(&p.ID, &p.Title, &p.Description, &p.ProductType, &p.Vendor, &tags); err != nil {
			return nil, err
		}
		p.Tags = tags
		products = append(products, p)
	}
	return products, rows.Err()
}
func metricsToModel(m *analytics.Metrics) *model.Metrics {
	out := &model.Metrics{
		RevenueCents:       int(m.RevenueCents),
		Orders:             m.Orders,
		AovCents:           int(m.AOVCents),
		UnitsSold:          m.UnitsSold,
		NewCustomers:       m.NewCustomers,
		ReturningCustomers: m.ReturningCustomers,
		ReturningRate:      m.ReturningRate,
	}
	for _, p := range m.TopProducts {
		out.TopProducts = append(out.TopProducts, &model.ProductStat{
			ProductID:    p.ProductID,
			Title:        p.Title,
			RevenueCents: int(p.RevenueCents),
			UnitsSold:    p.UnitsSold,
		})
	}
	for _, p := range m.BottomProducts {
		out.BottomProducts = append(out.BottomProducts, &model.ProductStat{
			ProductID:    p.ProductID,
			Title:        p.Title,
			RevenueCents: int(p.RevenueCents),
			UnitsSold:    p.UnitsSold,
		})
	}
	for _, v := range m.DeadStock {
		sku := v.SKU
		out.DeadStock = append(out.DeadStock, &model.VariantStat{
			VariantID:         v.VariantID,
			Sku:               &sku,
			Title:             v.Title,
			InventoryQty:      v.InventoryQty,
			DaysSinceLastSale: v.DaysSinceLastSale,
		})
	}
	for _, t := range m.Trend {
		out.Trend = append(out.Trend, &model.TimePoint{
			Date:         t.Date,
			RevenueCents: int(t.RevenueCents),
			Orders:       t.Orders,
		})
	}
	for _, c := range m.CohortRetention {
		out.CohortRetention = append(out.CohortRetention, &model.CohortRow{
			CohortMonth:   c.CohortMonth,
			ActivityMonth: c.ActivityMonth,
			Customers:     c.Customers,
			RetentionPct:  c.RetentionPct,
		})
	}
	for _, v := range m.InventoryVelocity {
		sku := v.SKU
		out.InventoryVelocity = append(out.InventoryVelocity, &model.VelocityStat{
			VariantID:      v.VariantID,
			Sku:            &sku,
			Title:          v.Title,
			UnitsPer30Days: v.UnitsPer30Days,
			UnitsPer90Days: v.UnitsPer90Days,
			InventoryQty:   v.InventoryQty,
		})
	}
	return out
}
